title: Robcamstone's Bookmarks
author:
  name: Robcamstone
description: >- # this means to ignore newlines until "baseurl:"
  

show_excerpts: false # set to true to show excerpts on the homepage or to false to hide excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%-d %B %Y"

# generate social links in footer
  social_links:
    # twitter: N/A
    github:  Robcamstone
    rss: rss
    # dribbble: N/A
    # facebook: robert.stonebanks
    # flickr:   N/A
    # instagram: N/A
    # linkedin: N/A
    # pinterest: N/A
    # youtube: Robcamstone
    youtube_channel: UCxGas6kcIvNZVIpZfTPKLug
    youtube_channel_name: Robcamstone
    # telegram: N/A
    # microdotblog: N/A

    # Mastodon instances
    # mastodon:
    # - username: N/A
    #   instance: example.com
    # - username: N/A
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
   - about.md
#   - bookmarks.md
#   - categories.md

# Build settings
timezone: Europe/London
markdown: kramdown
theme: minima
permalink: /:year-:month-:day-:title/

plugins:
 - jemoji
 - jekyll-feed
 - jekyll-sitemap
 - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
